(define (create-moire name seed)
	(let*
		(
			(image (car (gimp-image-new 4096 4096 RGB)))
			(main (car (gimp-layer-new image 4096 4096 RGBA-IMAGE "Main" 0 NORMAL-MODE)))
			(noise (car (gimp-layer-new image 4096 4096 RGB-IMAGE "Noise" 0 NORMAL-MODE)))
		)
		(gimp-image-insert-layer image main 0 0)
		(gimp-image-insert-layer image noise 0 1)
		(gimp-context-set-foreground '(0 0 0))
		(gimp-edit-blend main FG-TRANSPARENT-MODE NORMAL-MODE GRADIENT-LINEAR 100 0 REPEAT-TRIANGULAR FALSE FALSE 1 0 FALSE 0 0 4 4)
		(plug-in-solid-noise RUN-NONINTERACTIVE image noise TRUE FALSE seed 1 4 4)
		(plug-in-displace RUN-NONINTERACTIVE image main 10 10 1 1 noise noise 1)
		(gimp-image-remove-layer image noise)
		(gimp-context-set-interpolation INTERPOLATION-CUBIC)
		(gimp-image-scale image 512 512)
		(file-png-save RUN-NONINTERACTIVE image main name name 0 9 0 0 0 1 1)
		(gimp-image-delete image)
	)
)
